// stamps.js — Definición de los 12 sellos del pasaporte
// Cambia estos datos para personalizar el pasaporte

const STAMPS_DATA = [
  {
    id: "s01",
    name: "Museo Nacional",
    emoji: "🏛️",
    description: "Arte e historia de nuestra nación",
    color: "#7c4f1e",
    bg: "#f5e6d0",
  },
  {
    id: "s02",
    name: "Mercado Central",
    emoji: "🛒",
    description: "Sabores y aromas del pueblo",
    color: "#8b1a1a",
    bg: "#fde8e8",
  },
  {
    id: "s03",
    name: "Parque Nacional",
    emoji: "🌲",
    description: "Naturaleza en su estado puro",
    color: "#1a5c2e",
    bg: "#e0f5e6",
  },
  {
    id: "s04",
    name: "Catedral Mayor",
    emoji: "⛪",
    description: "Patrimonio arquitectónico",
    color: "#3a2c7a",
    bg: "#ede8fc",
  },
  {
    id: "s05",
    name: "Puerto Histórico",
    emoji: "⚓",
    description: "Cuna del comercio marítimo",
    color: "#0d4f7c",
    bg: "#ddf0ff",
  },
  {
    id: "s06",
    name: "Mirador del Valle",
    emoji: "🔭",
    description: "Vistas panorámicas inigualables",
    color: "#5c4a1a",
    bg: "#fdf4dc",
  },
  {
    id: "s07",
    name: "Ruinas Antiguas",
    emoji: "🗿",
    description: "Vestigios de civilizaciones pasadas",
    color: "#4a3825",
    bg: "#f0e8dc",
  },
  {
    id: "s08",
    name: "Playa de Cristal",
    emoji: "🏖️",
    description: "Aguas turquesas y arenas blancas",
    color: "#0a6b7c",
    bg: "#d9f5f8",
  },
  {
    id: "s09",
    name: "Barrio Colonial",
    emoji: "🏘️",
    description: "Calles empedradas con historia",
    color: "#7c2d5e",
    bg: "#fce8f4",
  },
  {
    id: "s10",
    name: "Jardín Botánico",
    emoji: "🌺",
    description: "Flora exótica y aromas únicos",
    color: "#3d6b1a",
    bg: "#e8f5d9",
  },
  {
    id: "s11",
    name: "Observatorio",
    emoji: "🌌",
    description: "El cosmos al alcance de la mano",
    color: "#1a1a5c",
    bg: "#e8e8fc",
  },
  {
    id: "s12",
    name: "Faro del Fin",
    emoji: "🗼",
    description: "El último punto del camino",
    color: "#5c1a1a",
    bg: "#fce8e8",
  },
];
